# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to=b'')),
                ('imagem', models.FileField(upload_to=b'')),
                ('categorias', models.CharField(choices=[('Windows', 'Windows'), ('Siga', 'Siga'), ('Acompanhamento de Sess\xe3o', 'Acompanhamento de Sess\xe3o'), ('Siga-gest\xe3o de conhecimento', 'Siga-gest\xe3o de conhecimento'), ('DRS Audi\xeancias', 'DRS Audi\xeancias'), ('Skype for Business', 'Skype for Business')], default='', max_length=250)),
            ],
        ),
    ]
