# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171030_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='categorias',
        ),
        migrations.AddField(
            model_name='video',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Categoria'),
        ),
    ]
